version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: movies
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
